// Dedicated Budget view and shared schedule edges, all synthetic accounts.
const assert=require('node:assert/strict'),{boot}=require('./app-harness.cjs'),tick=()=>new Promise(r=>setTimeout(r,45));
const cost={mode:'calculated',quantity:10,unit:'LF',unitRate:2,crew:2,hours:3,laborRate:30,burden:10,other:5,markup:20,includeLabor:false};
const seed={users:{a:{todo:{projects:{p:{name:'Pool'}},tasks:{t:{projectId:'p',title:'Tile',notes:'Original',cost,dueDate:'2026-11-02'},u:{projectId:'p',title:'Unplaced',budget:11.01,startDate:'2026-11-08',dueDate:'2026-11-10'},bad:{projectId:'p',title:'Invalid',budget:25,startDate:'2026-02-30',dueDate:'2026-11-10'},zero:{projectId:'p',title:' =SUM(A1)',notes:'\t@cmd\n"quote",comma',cost:{...cost,quantity:0,unitRate:4,other:0,markup:0}}},maps:{p:{budget:100,nodes:{b:{parent:'root',kind:'branch',title:'Finish'},i:{parent:'b',kind:'item',taskId:'t',start:'2026-10-31'},b2:{parent:'root',kind:'branch',title:'Finish'},dup:{parent:'b2',kind:'item',taskId:'t'},old:{parent:'b',kind:'item',title:'Flat',budget:7,desc:'Old'}}}},history:{}}},b:{todo:{projects:{p:{name:'Other'}},tasks:{t:{projectId:'p',title:'Other tile',cost,notes:'New user'}},maps:{p:{nodes:{i:{parent:'root',kind:'item',taskId:'t'}}}},history:{}}}}};
(async()=>{const {w,d,db}=await boot(seed,{user:{uid:'a',email:'a@test'}}),M=w.__oym,$=s=>d.querySelector(s),key=(el,k,opts={})=>el.dispatchEvent(new w.KeyboardEvent('keydown',{key:k,bubbles:true,cancelable:true,...opts}));M.setMapPid('p');M.setView('budget');await tick();assert.equal($('#v-budget').hidden,false);assert.equal(w.localStorage.getItem('oym_view'),'budget');assert.equal(d.querySelectorAll('.tab').length,5);assert.equal(d.querySelectorAll('.fin-table th').length,10);assert.match($('#financeHost').textContent,/Quantity needed/);
let data=M.financeData('p');assert.equal(data.B.root.alloc,73.01);assert.equal(data.B.dup.own,0);assert.equal(data.rows.find(r=>r.key==='n:dup').duplicate,true);assert.equal(data.rows.find(r=>r.key==='n:i').start,'2026-10-31');assert.equal(data.F.unscheduled,32);assert.equal(data.F.scheduled,68);assert.equal(data.F.days.has('2026-11-10'),true);for(const scale of ['week','month']){const p=M.financePeriods(data.F,scale);assert.equal(Math.round(p.reduce((a,b)=>a+b.amount,0)*100),6800);assert.equal(p.at(-1).cumulative,68)}
// Repeated section names do not accidentally reveal the wrong branch when filtering.
assert.equal(M.financeVisible(data,'Flat').rows.some(r=>r.key==='n:b2'),false);assert.equal(M.financeVisible(data,'Flat').scopeTotal,7);assert.equal(M.financeVisible(data,'','unknown').count,1);
const csv=M.financeCSV('p');assert(csv.startsWith('\ufeff'));assert(csv.includes('"\' =SUM(A1)"'));assert(csv.includes('"\'\t@cmd\n""quote"",comma"'));assert.equal(csv.match(/"Tile"/g).length,1);assert(!csv.includes('"section","Finish"'));assert.match(csv,/Scope total \$/);
let before=db.updates.length;await assert.rejects(M.financeSaveCell('p','n:i','unitRate','-1'));await assert.rejects(M.financeSaveCell('p','n:i','crew','1.5'));await assert.rejects(M.financeSaveCell('p','n:i','start','2026-02-30'));await assert.rejects(M.financeSaveCell('p','n:i','due','2026-10-01'));assert.equal(db.updates.length,before);
await M.financeSaveCell('p','n:i','unitRate','3');assert.equal(M.tasks.t.cost.includeLabor,false);assert.equal(M.tasks.t.cost.crew,2);assert.equal(M.tasks.t.cost.hours,3);assert.equal(M.tasks.t.cost.laborRate,30);assert.equal(M.tasks.t.cost.unitRate,3);assert.equal(db.get('users/a/todo/maps/p/nodes/dup/cost/unitRate'),3);assert.equal(M.financeData('p').B.root.alloc,85.01);
await M.financeSaveCell('p','n:i','includeLabor','true');assert.equal(M.costParts(M.tasks.t.cost).labor,198);await M.financeSaveCell('p','n:i','includeLabor','false');assert.equal(M.costParts(M.tasks.t.cost).labor,0);await M.financeSaveCell('p','n:i','notes','<img src=x>\nLong note');assert.equal(M.tasks.t.notes,'<img src=x>\nLong note');assert.equal(db.get('users/a/todo/maps/p/nodes/dup/desc'),M.tasks.t.notes);assert.equal(M.tasks.t.cost.unitRate,3);await M.financeSaveCell('p','t:u','due','2026-11-12');assert.equal(M.tasks.u.dueDate,'2026-11-12');await M.financeSaveCell('p','n:i','start','');assert.equal(M.tasks.t.startDate,'');assert.equal(M.financeData('p').rows.find(r=>r.key==='n:i').start,'');assert.equal(db.get('users/a/todo/maps/p/nodes/i/start'),undefined);
// One cell merges with current data, failed writes retain the draft, and Tab saves only one cell.
M.financeOpen('n:i','unitRate');let input=$('[data-fin-value]');input.value='5';input.dispatchEvent(new w.Event('input',{bubbles:true}));await db.ref('').update({'users/a/todo/tasks/t/cost/other':9});assert.equal($('[data-fin-value]'),input);assert.equal(input.value,'5');db.interceptNextUpdate(()=>Promise.reject(Error('Denied fixture')));$('[data-fin-save]').click();await tick();assert.match($('[data-fin-error]').textContent,/Denied/);assert.equal($('[data-fin-value]').value,'5');$('[data-fin-save]').click();await tick();assert.equal(M.tasks.t.cost.other,9);assert.equal(M.tasks.t.cost.unitRate,5);assert.equal($('.fin-edit'),null);
M.financeOpen('n:i','quantity');input=$('[data-fin-value]');input.value='12';key(input,'Tab');await tick();assert.equal(M.tasks.t.cost.quantity,12);assert.equal(M.finEdit.field,'unit');before=db.updates.length;key($('[data-fin-value]'),'Escape');assert.equal(db.updates.length,before);assert.equal($('.fin-edit'),null);M.financeOpen('n:old','total');input=$('[data-fin-value]');input.value='9.50';key(input,'Enter');await tick();assert.equal(db.get('users/a/todo/maps/p/nodes/old/budget'),9.5);if(M.finEdit)key($('[data-fin-value]'),'Escape');
M.financeOpen('n:i','unitRate');await db.ref('').update({'users/a/todo/tasks/t/cost':null,'users/a/todo/tasks/t/budget':30});$('[data-fin-save]').click();await tick();assert.match($('[data-fin-error]').textContent,/method changed/);assert.equal(M.tasks.t.budget,30);key($('[data-fin-value]'),'Escape');
// Navigation never silently drops the active draft.
M.financeOpen('n:i','total');let keep=$('[data-fin-value]');keep.value='Draft';keep.dispatchEvent(new w.Event('input',{bubbles:true}));$('[data-fin-details]').click();assert.equal($('[data-fin-value]'),keep);assert.match($('[data-fin-error]').textContent,/Save or Cancel/);$('[data-fin-filter]').value='unknown';$('[data-fin-filter]').dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal($('[data-fin-filter]').value,'all');assert.equal($('[data-fin-value]').value,'Draft');key(keep,'Escape');
// Add failures retain scope name and retry a single task ID.
$('[data-fin-new]').value='New scope';$('[data-fin-new]').dispatchEvent(new w.Event('input',{bubbles:true}));db.interceptNextUpdate(()=>Promise.reject(Error('Add denied')));await M.financeAddScope();assert.equal($('[data-fin-new]').value,'New scope');assert.match($('[data-fin-add-error]').textContent,/Add denied/);await M.financeAddScope();assert.equal(Object.values(M.tasks).filter(t=>t.title==='New scope').length,1);assert.equal(Object.values(M.maps.p.nodes).filter(n=>n.title==='New scope').length,0);
// Cancel keypress does not save; account switch invalidates draft and late UI response.
M.financeOpen('n:i','total');before=db.updates.length;key($('[data-fin-cancel]'),'Enter');await tick();assert.equal(db.updates.length,before);$('[data-fin-cancel]').click();M.financeOpen('n:i','total');let finish;db.interceptNextUpdate((patch,apply)=>new Promise(resolve=>{finish=()=>apply().then(resolve)}));$('[data-fin-save]').click();assert.equal($('[data-fin-cancel]').disabled,true);w.__setUser({uid:'b',email:'b@test'});await tick();finish();await tick();assert.equal(M.finEdit,null);assert.equal($('.fin-edit'),null);assert.equal(M.tasks.t.notes,'New user');assert.equal(db.get('users/b/todo/tasks/t/cost/unitRate'),2);
// Budget-enabled Timeline includes distant unplaced spending; plain schedule range remains unchanged.
await db.ref('').update({'users/b/todo/tasks/future':{title:'Future fee',projectId:'p',dueDate:'2027-06-01',budget:10}});const R=M.roadmapData('p','2026-09-28');const noFlow=M.gtRange(R,'2026-09-28',null),withFlow=M.gtRange(R,'2026-09-28',M.budgetFlow('p'));assert(withFlow.days>noFlow.days);assert(withFlow.d1.toISOString().slice(0,10)>'2027-06-01');
// Every nonempty invalid endpoint is unscheduled, reversed valid ranges normalize, DST conserves cents.
const F={days:new Map([['2026-10-31',.333333],['2026-11-01',.333333],['2026-11-02',.333334]])};for(const scale of ['week','month']){const p=M.financePeriods(F,scale);assert.equal(Math.round(p.reduce((a,b)=>a+b.amount,0)*100),100)}assert.equal(M.budgetSpan({startDate:'2026-02-30',dueDate:'2026-10-01'},true).invalid,true);w.close();console.log('finance: canonical dedupe, inherited dates, invalid dates, unplaced schedule/reserve, cents, scope CSV safety, DIY, one-cell merging/retry/conflict/keyboard and account isolation passed');})().catch(e=>{console.error(e);process.exit(1)});
