const assert=require('node:assert/strict'),{boot}=require('./app-harness.cjs'),tick=()=>new Promise(r=>setTimeout(r,45));
const cost={mode:'calculated',quantity:10,unit:'LF',unitRate:2,crew:1,hours:2,laborRate:30,burden:0,other:0,markup:0,includeLabor:false};
const data={projects:{p:{name:'Pool'},q:{name:'Other'}},tasks:{a:{projectId:'p',title:'Alpha',cost,notes:'Original'},b:{projectId:'p',title:'Beta',cost:{...cost,quantity:3}},c:{projectId:'p',title:'Flat',budget:7}},maps:{p:{nodes:{a:{parent:'root',kind:'item',taskId:'a'},b:{parent:'root',kind:'item',taskId:'b'},dup:{parent:'root',kind:'item',taskId:'a'},c:{parent:'root',kind:'item',taskId:'c'}}}},history:{}};
(async()=>{const {w,d,db}=await boot({users:{one:{todo:data},two:{todo:{...data,projects:{q:{name:'Second account'}}}}}},{user:{uid:'one',email:'one@test'}}),M=w.__oym,$=x=>d.querySelector(x),key=(t,k,extra={})=>t.dispatchEvent(new w.KeyboardEvent('keydown',{key:k,bubbles:true,cancelable:true,...extra}));M.setMapPid('p');M.setView('budget');const before=db.updates.length;
assert(M.financeSelect('n:a','quantity'));assert.equal(d.activeElement.dataset.finField,'quantity');key(d.activeElement,'ArrowRight');assert.equal(d.activeElement.dataset.finField,'unit');key(d.activeElement,'ArrowDown');assert.equal(d.activeElement.dataset.finRow,'n:b');assert.equal(db.updates.length,before);assert.equal($('.fin-selected-column').dataset.finColumn,'unit');assert.equal(d.querySelectorAll('[data-fin-row="n:dup"]').length,0);
M.financeSelect('n:a','quantity');M.renderFinance();assert.equal(d.activeElement.dataset.finField,'quantity');key(d.activeElement,'4');assert.equal(M.finEdit.value,'4');assert.equal($('[data-fin-value]').value,'4');assert.equal(db.updates.length,before);key($('[data-fin-value]'),'Escape');assert.equal(M.finEdit,null);assert.equal(d.activeElement.dataset.finField,'quantity');key(d.activeElement,'F2');$('[data-fin-value]').value='12';key($('[data-fin-value]'),'Tab');await tick();assert.equal(M.tasks.a.cost.quantity,12);assert.equal(M.tasks.a.cost.includeLabor,false);assert.equal(M.finEdit.field,'unit');const select=$('[data-fin-value]');key(select,'ArrowDown');assert.equal(M.finEdit.field,'unit');key(select,'Escape');
M.financeSelect('n:a','unitRate');key(d.activeElement,'Enter');$('[data-fin-value]').value='-1';await M.financeCommit();assert.match($('[data-fin-error]').textContent,/nonnegative/);assert.equal(M.finEdit.value,'-1');$('[data-fin-value]').value='5';db.interceptNextUpdate(()=>Promise.reject(new Error('Rejected')));await M.financeCommit();assert.match($('[data-fin-error]').textContent,/Rejected/);await M.financeCommit();assert.equal(M.finEdit,null);assert.equal(M.tasks.a.cost.unitRate,5);
// Palette preserves draft and exact caret, navigation commands blocked until explicit cancellation.
M.financeOpen('n:a','quantity');const input=$('[data-fin-value]');input.value='123';input.setSelectionRange(1,2);key(input,'k',{ctrlKey:true});assert($('#commandDialog').open);assert.equal(M.finEdit.field,'quantity');assert.equal(M.commandRun('home'),false);assert.match($('#commandStatus').textContent,/Save or Cancel/);key($('#commandSearch'),'Escape');assert.equal(d.activeElement,input);assert.equal(input.selectionStart,1);assert.equal(input.selectionEnd,2);assert.equal(input.value,'123');key(input,'Escape');
// Help, search, native typing, sequences, repeat/composition and focus cancellation.
key(d.body,'?');assert($('#commandDialog').open);$('#commandSearch').value='Calendar';$('#commandSearch').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal($('#commandList [data-command]').dataset.command,'calendar');key($('#commandSearch'),'Enter');assert.equal(w.localStorage.getItem('oym_view'),'calendar');key(d.body,'g');key(d.body,'p');assert.equal(w.localStorage.getItem('oym_view'),'projects');const search=$('[data-project-search]');search.focus();key(search,'g');key(search,'b');assert.equal(w.localStorage.getItem('oym_view'),'projects');key(d.body,'g',{isComposing:true});key(d.body,'t');assert.equal(w.localStorage.getItem('oym_view'),'projects');key(d.body,'g');key(d.body,'p',{isComposing:true});key(d.body,'p');assert.equal(w.localStorage.getItem('oym_view'),'projects');key(d.body,'g',{repeat:true});key(d.body,'t');assert.equal(w.localStorage.getItem('oym_view'),'projects');search.blur();key(d.body,'g');search.focus();key(d.body,'t');assert.equal(w.localStorage.getItem('oym_view'),'projects');M.commandRun('budget');key(d.body,'/');assert.equal(d.activeElement,$('[data-fin-search]'));
// Multiline notes keep newline and Escape restores selected cell. Account switches clear dialog/selection/draft.
$('[data-fin-notes]').click();M.financeOpen('n:a','notes');const note=$('[data-fin-value]'),ev=new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true});note.dispatchEvent(ev);assert.equal(ev.defaultPrevented,false);key(note,'Escape');assert.equal(d.activeElement.dataset.finField,'notes');M.commandOpen();w.__setUser({uid:'two',email:'two@test'});await tick();assert.equal($('#commandDialog').open,false);assert.equal(M.finSelection,null);assert.equal(M.finEdit,null);assert.equal(db.updates.length,before+2);w.close();console.log('keyboard spreadsheet: selection, arrows/no writes, numeric replacement, save/retry, native controls, palette draft/caret, guarded sequences and account cleanup passed');
})().catch(e=>{console.error(e);process.exit(1)});
