// Native-animation + responsive verification, synthetic read-only Firebase; no external traffic.
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='todo.test'){const f=path.join(root,u.pathname==='/'?'index.html':u.pathname);if(fs.existsSync(f))return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':'application/octet-stream'})}return r.abort()});
 await p.addInitScript(()=>{
 const seed={projects:{p:{name:'Bring the vision to life',status:'active'},empty:{name:'Future project',status:'active'}},tasks:{t:{title:'Prepare launch plan',projectId:'p',side:'career',dueDate:'2026-10-01'},done:{title:'Approved the concept',projectId:'p',completed:true,completedAt:'2026-09-28T18:00:00Z'}},history:{},maps:{p:{nodes:{later:{parent:'root',kind:'branch',title:'Delivery',dx:60,order:1},early:{parent:'root',kind:'branch',title:'Planning',dy:50,order:2},t1:{parent:'later',kind:'item',title:'Publish',due:'2026-10-10',order:1},t2:{parent:'later',kind:'item',title:'Review',due:'2026-10-03',order:2},t3:{parent:'early',kind:'item',title:'Start with a sketch',due:'2026-10-01'},t4:{parent:'early',kind:'item',title:'An idea without a date'}}}}};const user={uid:'owner',email:'dyap123@gmail.com',emailVerified:true};window.firebase={apps:[],initializeApp(){this.apps.push({})},auth:Object.assign(()=>({onAuthStateChanged:f=>setTimeout(()=>f(user),0),getRedirectResult:async()=>{}}),{GoogleAuthProvider:function(){this.setCustomParameters=()=>{}}}),database:()=>({ref:(x='')=>({on:(e,f)=>f({val:()=>x==='.info/connected'?true:x.split('/').slice(1).reduce((v,k)=>v?.[k],seed)||null}),off(){},push:()=>({key:'fixture'}),update:()=>Promise.reject(Error('Read-only fixture'))})})};
 });
 await p.goto('http://todo.test/');await p.locator('#gate').waitFor({state:'hidden'});await p.locator('[data-view="tasks"]').click();assert.equal(await p.locator('.tabs .tab:last-child').textContent(),'Dashboard');await p.screenshot({path:'/private/tmp/oy-todo-projects-desktop.png',fullPage:true});
 await p.locator('[data-project-side="career"][data-project-toggle="p"]').click();assert(await p.locator('.task[data-id="t"]').isVisible());
 await p.getByRole('button',{name:'Settings',exact:true}).click();assert(await p.getByRole('dialog',{name:'Settings'}).isVisible());await p.screenshot({path:'/private/tmp/oy-todo-settings-desktop.png',fullPage:true});await p.keyboard.press('Escape');assert(await p.locator('#settingsBtn').evaluate(el=>el===document.activeElement));
 await p.evaluate(()=>window.__oym.setView('map'));await p.evaluate(()=>{window.savedWorld=document.querySelector('#mapWorld');window.savedTile=document.querySelector('[data-nid="later"]');window.savedCamera=window.savedWorld.style.transform;window.savedPosition=window.savedTile.style.cssText});
 await p.getByRole('button',{name:'Chronology',exact:true}).click();assert(await p.evaluate(()=>document.querySelector('#mapWorld')===window.savedWorld&&document.querySelector('[data-nid="later"]')===window.savedTile));
 const motion=await p.evaluate(()=>{const tile=window.savedTile;return {animations:tile.getAnimations().length,transform:getComputedStyle(tile).transform,x:tile.getBoundingClientRect().x}});assert(motion.animations>0,'native tile animation must exist without anime CDN');await p.waitForTimeout(180);const intermediate=await p.locator('[data-nid="later"]').evaluate(el=>el.getBoundingClientRect().x);assert.notEqual(intermediate,motion.x,'tile must interpolate, not jump');await p.waitForTimeout(800);assert.equal(await p.locator('[data-nid="later"]').evaluate(el=>getComputedStyle(el).transform),'none');
 await p.screenshot({path:'/private/tmp/oy-todo-chronology-desktop.png',fullPage:true});
 await p.getByRole('button',{name:'Play timeline',exact:true}).click();await p.waitForTimeout(500);assert(+(await p.locator('[data-chrono-scrub]').inputValue())>0);await p.getByRole('button',{name:'Pause',exact:true}).click();
 await p.getByRole('button',{name:'Back to map',exact:true}).click();await p.waitForTimeout(900);assert(await p.evaluate(()=>window.savedTile.style.cssText===window.savedPosition&&window.savedWorld.style.transform===window.savedCamera));
 await p.setViewportSize({width:390,height:844});await p.locator('[data-view="tasks"]').click();assert.equal(await p.evaluate(()=>document.body.scrollWidth),390);await p.screenshot({path:'/private/tmp/oy-todo-projects-mobile.png',fullPage:true});
 await p.getByRole('button',{name:'Settings',exact:true}).click();assert.equal(await p.evaluate(()=>document.body.scrollWidth),390);await p.screenshot({path:'/private/tmp/oy-todo-settings-mobile.png',fullPage:true});await p.keyboard.press('Escape');
 await p.evaluate(()=>window.__oym.setView('map'));await p.locator('#exportBtn').click();await p.locator('[data-extab="markdown"]').click();assert.equal(await p.locator('[data-exg="tab"] button').count(),6);assert.equal(await p.locator('[data-export-project]').inputValue(),'p');await p.keyboard.press('Escape');
 await p.emulateMedia({reducedMotion:'reduce'});await p.getByRole('button',{name:'Chronology',exact:true}).click();assert.equal(await p.locator('[data-nid="later"]').evaluate(el=>el.getAnimations().length),0);await p.getByRole('button',{name:'Fit',exact:true}).click();await p.screenshot({path:'/private/tmp/oy-todo-chronology-mobile.png',fullPage:true});assert.equal(await p.evaluate(()=>document.body.scrollWidth),390);
 await p.locator('[data-view="dashboard"]').click();assert(await p.locator('#dashboardDone').isVisible());await p.screenshot({path:'/private/tmp/oy-todo-dashboard-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('navigation browser: project/settings/dashboard/mobile, same-node native animation interpolation, exact restoration, Markdown keyboard and reduced motion passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
