const assert=require('node:assert/strict'),{boot}=require('./app-harness.cjs');const tick=()=>new Promise(r=>setTimeout(r,40));let checks=0;const check=(n,f)=>{f();checks++;console.log('ok',n)};
(async()=>{
const seed={projects:{p:{name:'Roadmap <img src=x>',status:'active'},q:{name:'Another project',status:'active'}},trackingCategories:{'cat-health':{name:'Health & learning',color:'#127abc'}},sides:{p:{side:'career',private:true}},maps:{p:{nodes:{branch:{kind:'branch',parent:'root',title:'Branch',dx:47,dy:19},i:{kind:'item',parent:'branch',taskId:'open',title:'Open'}}}},tasks:{open:{title:'Open',projectId:'p',side:'career',dueDate:'2026-10-05',notes:'Keep notes'},done:{title:'Finished',projectId:'p',side:'career',completed:true,completedAt:'2026-09-27T12:30:00Z',progress:100},cross:{title:'Cross category',projectId:'p',side:'openyap'},other:{title:'Not ours',projectId:'q',side:'career'}},history:{done:{taskId:'done',projectId:'p',title:'Finished',side:'career',completedAt:'2026-09-27T12:30:00Z',notes:'Historical note',private:true},repeat:{projectId:'p',title:'Repeat occurrence',side:'career',completedAt:'2026-09-26T10:00:00Z'},legacy:{taskId:'done',title:'Legacy snapshot',side:'career',completedAt:'2026-09-25T10:00:00Z'},different:{taskId:'done',projectId:'q',title:'Other historical project',side:'career',completedAt:'2026-09-24T10:00:00Z'},other:{taskId:'other',projectId:'q',side:'career',title:'Other',completedAt:'2026-09-23T10:00:00Z'}}};
const {w,d,db}=await boot({users:{alice:{todo:seed},bob:{todo:{}}}},{user:{uid:'alice',email:'alice@example.com'}}),M=w.__oym,P='users/alice/todo/';const before=JSON.parse(JSON.stringify(db.get(P))),changes=db.updates.length;
check('each collapsed project has category action and unassigned group does not',()=>{assert(d.querySelector('[data-project-group="p"] [data-project-category="p"]'));assert(!d.querySelector('[data-project-group=""] [data-project-category]'))});
d.querySelector('[data-project-group="p"] [data-project-category]').click();check('accessible category chooser explains tasks and completed work, supports custom categories and escaped project name',()=>{assert(!d.querySelector('#projectCategoryBack').hidden);assert.equal(d.activeElement,d.querySelector('#projectCategorySelect'));assert.match(d.querySelector('#projectCategoryHelp').textContent,/including completed work/);assert(d.querySelector('#projectCategorySelect [value="cat-health"]'));assert(!d.querySelector('#projectCategoryBack img'));assert.match(d.querySelector('.project-category-name').textContent,/<img src=x>/)});
d.querySelector('#projectCategorySelect').value='cat-health';d.querySelector('#projectCategoryForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();
check('one atomic workspace update moves project all tasks and matching completion snapshots',()=>{assert.equal(db.updates.length,changes+1);const patch=db.updates.at(-1);assert.equal(patch[P+'sides/p/side'],'cat-health');for(const id of ['open','done','cross'])assert.equal(patch[P+'tasks/'+id+'/side'],'cat-health');for(const id of ['done','repeat','legacy'])assert.equal(patch[P+'history/'+id+'/side'],'cat-health');assert(!Object.keys(patch).some(k=>k.includes('history/different')||k.includes('history/other')||k.includes('tasks/other')))});
check('IDs maps offsets task dates completion details privacy and unrelated history remain intact',()=>{const now=db.get(P);assert.deepEqual(now.maps,before.maps);assert.deepEqual(now.projects,before.projects);assert(now.sides.p.private);for(const id of ['open','done','cross']){const a={...now.tasks[id]},b={...before.tasks[id]};delete a.side;delete b.side;assert.deepEqual(a,b)}for(const id of ['done','repeat','legacy']){const a={...now.history[id]},b={...before.history[id]};delete a.side;delete b.side;assert.deepEqual(a,b)}assert.deepEqual(now.history.different,before.history.different);assert.deepEqual(now.history.other,before.history.other)});
check('destination selected and project expanded with keyboard focus',()=>{assert.equal(d.querySelector('#sides').dataset.m,'cat-health');const b=d.querySelector('[data-project-side="cat-health"][data-project-toggle="p"]');assert.equal(b.getAttribute('aria-expanded'),'true');assert.equal(d.activeElement,b);assert(!d.querySelector('[data-project-side="career"][data-project-toggle="p"]'));assert(d.querySelector('.task[data-id="open"]'))});
d.querySelector('[data-project-completed="p"]').click();check('completed project filtering finds moved rows under destination category',()=>{assert.match(d.querySelector('#doneList').textContent,/Finished/);assert.match(d.querySelector('#doneList').textContent,/Repeat occurrence/);assert(!d.querySelector('#doneList').textContent.includes('Other historical project'))});
M.setMapPid('p');d.querySelector('[data-view="map"]').click();await tick();check('selected Map top exposes category action',()=>assert(d.querySelector('.map-bar [data-project-category="p"]')));
d.querySelector('.map-bar [data-project-category="p"]').click();d.querySelector('#projectCategorySelect').value='career';db.interceptNextUpdate(()=>Promise.reject(Error('Permission denied fixture')));d.querySelector('#projectCategoryForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();check('failed move keeps dialog actionable and leaves data/category unchanged',()=>{assert(!d.querySelector('#projectCategoryBack').hidden);assert.match(d.querySelector('#projectCategoryError').textContent,/Permission denied/);assert(!d.querySelector('#projectCategoryForm [type="submit"]').disabled);assert.equal(db.get(P+'sides/p/side'),'cat-health')});
d.querySelector('#projectCategorySelect').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));check('Escape closes without writes',()=>assert(d.querySelector('#projectCategoryBack').hidden));
d.querySelector('[data-nid="root"]').click();d.querySelector('[data-mside-set="career"]').click();check('old Map category segment opens same safe workflow',()=>{assert(!d.querySelector('#projectCategoryBack').hidden);assert.equal(d.querySelector('#projectCategorySelect').value,'career')});
let rejectLate;db.interceptNextUpdate(()=>new Promise((resolve,reject)=>{rejectLate=reject}));d.querySelector('#projectCategoryForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));w.__setUser({uid:'bob',email:'bob@example.com'});rejectLate(Error('Old account failure'));await tick();check('account change clears dialog and ignores late errors/UI effects',()=>{assert(d.querySelector('#projectCategoryBack').hidden);assert.equal(d.querySelector('#projectCategoryBody').textContent,'');assert(!d.body.textContent.includes('Old account failure'));assert(!d.body.textContent.includes('Roadmap <img'));assert.equal(Object.keys(M.tasks).length,0)});
w.__setUser({uid:'alice',email:'alice@example.com'});await tick();d.querySelector('[data-view="tasks"]').click();d.querySelector('#v-tasks [data-project-category="p"]').click();let resolveLate;db.interceptNextUpdate(()=>new Promise(resolve=>{resolveLate=resolve}));d.querySelector('#projectCategorySelect').value='openyap';d.querySelector('#projectCategoryForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));w.__setUser({uid:'bob',email:'bob@example.com'});resolveLate();await tick();check('late success cannot reopen or select old project in another account',()=>{assert(d.querySelector('#projectCategoryBack').hidden);assert(!d.querySelector('#toast').textContent.includes('Project and tasks moved'));assert(!d.querySelector('[data-project-toggle="p"]'));assert.equal(Object.keys(M.tasks).length,0)});
w.close();console.log('project-category: '+checks+' passed');
})().catch(e=>{console.error(e);process.exit(1)});
