process.env.TZ='America/Los_Angeles';
const assert=require('node:assert/strict'),fs=require('fs'),{execFileSync}=require('child_process'),{boot}=require('./app-harness.cjs');const tick=()=>new Promise(r=>setTimeout(r,40));
(async()=>{const nodes={unknown:{kind:'branch',parent:'root',title:'Older completion',completed:true},b:{kind:'branch',parent:'root',title:'Selected branch',desc:'ANCESTOR SECRET DESCRIPTION'},t:{kind:'topic',parent:'b',title:'Selected topic'},i:{kind:'item',parent:'t',taskId:'a',title:'Stale title',due:'2026-10-01'},x:{kind:'branch',parent:'root',title:'EXCLUDED BRANCH'},xi:{kind:'item',parent:'x',title:'EXCLUDED ITEM',due:'2026-10-02'},private:{kind:'branch',parent:'root',title:'PRIVATE BRANCH',private:true},pi:{kind:'item',parent:'private',title:'PRIVATE ITEM'},pt:{kind:'item',parent:'t',taskId:'secret',title:'PRIVATE LINKED'},long:{kind:'item',parent:'t',title:'A deliberately long additional task label to exercise fitting and avoid collisions on printed maps',due:'2026-10-04'}};const {w,d,db}=await boot({users:{a:{todo:{projects:{p:{name:'Synthetic plan'}},tasks:{a:{title:'Canonical selected task',projectId:'p',notes:'LONG EXPLANATORY NOTES',dueDate:'2026-10-01'},secret:{title:'PRIVATE TASK TITLE',projectId:'p',private:true}},history:{},maps:{p:{nodes}}}},b:{todo:{}}}},{user:{uid:'a',email:'a@test.com'}}),M=w.__oym;M.setMapPid('p');
const beforeTasks=JSON.stringify(M.tasks),hist=JSON.stringify(M.hist);await M.mapSetNodeCompletion('p','t','save','2026-09-20T22:45');await M.mapSetNodeCompletion('p','t','save','2026-09-19T23:15');let n=M.maps.p.nodes.t;assert(n.completed);assert.equal(Object.keys(n.completionEvents).length,2);assert(Object.values(n.completionEvents).some(e=>e.previousCompletedAt?.includes('2026-09-21')));assert.equal(JSON.stringify(M.tasks),beforeTasks);assert.equal(JSON.stringify(M.hist),hist);assert.equal(M.entries().length,0);assert.match(M.mapMarkdown('p'),/Completion event: date edited/);await assert.rejects(M.mapSetNodeCompletion('p','b','save','2027-01-01T10:00'));await assert.rejects(M.mapSetNodeCompletion('p','i','save','2026-09-20T09:00'));
const save=(name,o)=>{const pdf=M.buildRoadmap({pid:'p',paper:'tabloid',...o});for(let i=1;i<=pdf.getNumberOfPages();i++){pdf.setPage(i);assert.deepEqual([pdf.internal.pageSize.getWidth(),pdf.internal.pageSize.getHeight()].sort((a,b)=>a-b),[792,1224])}const path='/private/tmp/oy-todo-'+name+'.pdf';fs.writeFileSync(path,Buffer.from(pdf.output('arraybuffer')));return {pdf,text:execFileSync('pdftotext',[path,'-'],{encoding:'utf8'})}};
const excluded=['unknown','b','t','x','xi','long'];const selected=save('selected-roadmap',{excluded,map:true});assert.match(selected.text,/Canonical selected task/);assert.match(selected.text,/Selected branch/);assert(!selected.text.includes('EXCLUDED'));assert(!selected.text.includes('PRIVATE'));assert(!selected.text.includes('LONG EXPLANATORY'));assert(!selected.text.includes('ANCESTOR SECRET'));assert.equal(selected.pdf.getNumberOfPages(),3);
const map=save('map-only',{time:false,schedule:false,map:true});assert.equal(map.pdf.getNumberOfPages(),1,'map-only export keeps every selected node on one zoomable sheet');assert(!map.text.includes('Schedule'));assert.match(map.text,/2026-09-19/);assert(!map.text.includes('PRIVATE'));assert.match(map.text,/date unknown/);
const both=save('full-roadmap',{map:true,desc:true});assert.match(both.text,/LONG EXPLANATORY NOTES/);assert.match(both.text,/Completed/);assert(!both.text.includes('PRIVATE'));assert(!both.text.includes('Generated'),'combined Roadmap output omits the generated-date stamp');assert.match(fs.readFileSync('/private/tmp/oy-todo-full-roadmap.pdf','latin1'),/\/OpenAction \[[^\]]+\/FitH null\]/,'combined Roadmap keeps its default first-page view');
const explicit=save('private-roadmap',{map:true,private:true});assert.match(explicit.text,/PRIVATE TASK TITLE/);
for(const paper of ['letter','a4']){const pdf=M.buildRoadmap({pid:'p',paper,time:false,schedule:false,map:true});assert.deepEqual([pdf.internal.pageSize.getWidth(),pdf.internal.pageSize.getHeight()].sort((a,b)=>a-b),paper==='letter'?[612,792]:[595.28,841.89])}
const brief=M.buildBrief({pid:'p',paper:'tabloid',map:true,time:true,desc:false,notes:false});for(let i=1;i<=brief.getNumberOfPages();i++){brief.setPage(i);assert.deepEqual([brief.internal.pageSize.getWidth(),brief.internal.pageSize.getHeight()].sort((a,b)=>a-b),[792,1224])}
M.roadmapToggle('p','x');assert(M.roadmapExcluded('p').has('xi'));assert.equal(M.briefExcluded('p').size,0);assert.throws(()=>M.buildRoadmap({pid:'p',time:false,schedule:false,map:false}),/Choose/);
await M.mapSetNodeCompletion('p','t','reopen');n=M.maps.p.nodes.t;assert.equal(n.completed,false);assert(!n.completedAt);assert.equal(Object.keys(n.completionEvents).length,3);assert(Object.values(n.completionEvents).some(e=>e.action==='reopened'&&e.previousCompletedAt));assert.equal(JSON.stringify(M.tasks),beforeTasks);d.querySelector('[data-view="map"]').click();d.querySelector('[data-nid="t"]').click();assert.match(d.querySelector('[data-node-completion]').textContent,/Completion history \(3\)/);assert.match(d.querySelector('[data-node-completion]').textContent,/Child tasks: 0 of 3/);
const writes=db.updates.length;db.interceptNextUpdate(()=>Promise.reject(Error('Denied fixture')));await assert.rejects(M.mapSetNodeCompletion('p','b','save','2026-09-20T09:00'));assert.equal(db.updates.length,writes);assert(!M.maps.p.nodes.b.completed);w.__setUser({uid:'b',email:'b@test.com'});await tick();assert(!d.querySelector('[data-node-completion]'));assert.equal(M.roadmapExcluded('p').size,0);w.close();console.log('roadmap/completion: real PDF dimensions/content/selection/privacy; compact defaults; node completion edit/reopen history, task independence and account isolation passed');})().catch(e=>{console.error(e);process.exit(1)});
