// Scope rates and notes edited directly on Timeline, using synthetic isolated accounts.
const assert=require('node:assert/strict'),{boot}=require('./app-harness.cjs'),tick=()=>new Promise(r=>setTimeout(r,45));
const cost={mode:'calculated',quantity:253,unit:'LF',unitRate:10,crew:2,hours:16,laborRate:35,burden:35,other:100,markup:20,includeLabor:false};
const zero={...cost,quantity:0,unit:'SF',unitRate:4,other:0};
const seed={users:{a:{todo:{projects:{p:{name:'Pool'},q:{name:'Other map'}},sides:{p:{side:'career'}},history:{},tasks:{t:{title:'Tile',notes:'Canonical notes',projectId:'p',side:'career',startDate:'2026-10-05',dueDate:'2026-10-06',cost},z:{title:'Pebble',projectId:'p',side:'career',dueDate:'2026-10-07',cost:zero}},maps:{p:{nodes:{b:{parent:'root',kind:'branch',title:'Finish',desc:'Branch notes'},i:{parent:'b',kind:'item',taskId:'t',title:'Stale',desc:'Stale notes',cost:zero},zero:{parent:'b',kind:'item',taskId:'z',title:'Pebble'},old:{parent:'b',kind:'item',title:'Old scope',due:'2026-10-08',budget:100,desc:'Old notes'}}},q:{nodes:{also:{parent:'root',kind:'item',taskId:'t'}}}}}},b:{todo:{projects:{p:{name:'New pool'}},tasks:{t:{title:'Other user',notes:'Their notes',cost}},maps:{p:{nodes:{i:{kind:'item',taskId:'t'}}}},history:{}}}}};
(async()=>{const {w,d,db}=await boot(seed,{user:{uid:'a',email:'a@test.com'}}),M=w.__oym,$=s=>d.querySelector(s);M.setMapPid('p');$('[data-view="timeline"]').click();await tick();assert.equal(M.gtUnits,false);assert.equal(M.gtDescriptions,false);assert.equal($('.gt-description'),null);$('[data-gt-units]').click();await tick();assert.equal(M.budgetOn,true);assert.equal(M.gtUnits,true);assert.equal(w.localStorage.getItem('oym_gtunits'),'1');assert.equal($('.gt-row[data-grow="i"] [data-gt-rate]').textContent,'$10 / LF');assert.equal($('.gt-row[data-grow="zero"] [data-gt-rate]').textContent,'$4 / SF');assert.equal($('.gt-row[data-grow="old"] [data-gt-rate]'),null);assert($('.gt-row[data-grow="old"] [data-budget]'));assert.match($('.budget-bar').textContent,/Allocated \$3,256/);
const writes=db.updates.length;await assert.rejects(M.gtSaveRate('p','i','-1'));await assert.rejects(M.gtSaveRate('p','old','10'));assert.equal(db.updates.length,writes);await M.gtSaveRate('p','i','12.50');assert.deepEqual(JSON.parse(JSON.stringify(M.tasks.t.cost)),{...cost,unitRate:12.5});assert.equal(db.get('users/a/todo/maps/q/nodes/also/cost/unitRate'),12.5);assert.equal(db.get('users/a/todo/tasks/t/notes'),'Canonical notes');assert.equal(M.budgetData('p').root.total,4015);assert.equal(M.budgetFlow('p').scheduled,4015);assert.equal(M.budgetFlow('p').days.get('2026-10-05'),1957.5);
M.gtOpenEditor('i','rate');await tick();let field=$('[data-gt-value]');field.value='14';field.dispatchEvent(new w.Event('input',{bubbles:true}));assert.match($('[data-gt-preview]').textContent,/\$4,370.40/);assert.equal(M.tasks.t.cost.unitRate,12.5);db.interceptNextUpdate(()=>Promise.reject(new Error('Denied for test')));$('[data-gt-edit-save]').click();await tick();assert.match($('[data-gt-error]').textContent,/Denied/);assert.equal($('[data-gt-value]').value,'14');assert.equal($('[data-gt-edit-save]').disabled,false);$('[data-gt-edit-save]').click();await tick();assert.equal(M.tasks.t.cost.unitRate,14);assert.equal($('.gt-editor'),null);
// Escape cancels without a write; buttons are not accidentally handled as input Enter.
M.gtOpenEditor('i','rate');let before=db.updates.length;const cancel=$('[data-gt-edit-cancel]');cancel.focus();cancel.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));await tick();assert.equal(db.updates.length,before);cancel.click();assert.equal($('.gt-editor'),null);M.gtOpenEditor('i','rate');$('[data-gt-value]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert.equal(db.updates.length,before);assert.equal($('.gt-editor'),null);
// Full wrapped descriptions derive from canonical task notes, including deliberate empty text.
$('[data-gt-descriptions]').click();await tick();assert.equal(M.gtDescriptions,true);assert.equal(w.localStorage.getItem('oym_gtdesc'),'1');assert.equal($('.gt-row[data-grow="b"] .gt-description').textContent,'Branch notes');assert.equal($('.gt-row[data-grow="i"] .gt-description').textContent,'Canonical notes');const note='<img src=x onerror=alert(1)>\nhttps://source.test/'+('long'.repeat(70));const pricing=JSON.stringify(M.tasks.t.cost);await M.gtSaveNotes('p','i',note);await tick();assert.equal($('.gt-row[data-grow="i"] .gt-description').textContent,note);assert.equal($('.gt-description img'),null);assert.equal(db.get('users/a/todo/maps/q/nodes/also/desc'),note);assert.equal(JSON.stringify(M.tasks.t.cost),pricing);await M.gtSaveNotes('p','old','Unlinked changed');assert.equal(db.get('users/a/todo/maps/p/nodes/old/desc'),'Unlinked changed');assert.equal(db.get('users/a/todo/maps/p/nodes/old/taskId'),undefined);await M.gtSaveNotes('p','b','Branch changed');assert.equal(M.maps.p.nodes.b.desc,'Branch changed');await M.gtSaveNotes('p','i','');assert.equal(M.tasks.t.notes,'');assert.equal(db.get('users/a/todo/maps/p/nodes/i/desc'),undefined);
M.gtOpenEditor('i','notes');field=$('[data-gt-value]');field.value='A draft';field.dispatchEvent(new w.Event('input',{bubbles:true}));db.interceptNextUpdate(()=>Promise.reject(new Error('Notes denied')));$('[data-gt-edit-save]').click();await tick();assert.match($('[data-gt-error]').textContent,/Notes denied/);assert.equal($('[data-gt-value]').value,'A draft');$('[data-gt-edit-save]').click();await tick();assert.equal(M.tasks.t.notes,'A draft');
// An account switch cannot reuse old rate/notes drafts or late UI callbacks.
M.gtOpenEditor('i','notes');const oldEpoch=Number($('.cost-editor')?.dataset.costEpoch||1);let finish;db.interceptNextUpdate((patch,apply)=>new Promise(resolve=>{finish=()=>apply().then(resolve)}));$('[data-gt-edit-save]').click();w.__setUser({uid:'b',email:'b@test.com'});await tick();finish();await tick();assert.equal(db.get('users/b/todo/tasks/t/notes'),'Their notes');assert.equal($('.gt-editor'),null);await assert.rejects(M.gtSaveRate('p','i','3',oldEpoch),/Account changed/);await assert.rejects(M.gtSaveNotes('p','i','wrong',oldEpoch),/Account changed/);w.close();console.log('timeline editing: unit/total presentation, quantity-zero rate, preserved DIY inputs, atomic rate/notes edits, flow rollups, validation, retry/cancel, canonical wrapped descriptions and account isolation passed');})().catch(e=>{console.error(e);process.exit(1)});
