const assert=require('node:assert/strict');
const {boot}=require('./app-harness.cjs');
const tick=(ms=40)=>new Promise(r=>setTimeout(r,ms));
let checks=0;const check=(name,fn)=>{fn();checks++;console.log('ok',name)};
const user=uid=>({uid,email:uid+'@example.com',emailVerified:false});
const fixture=(name='Alpha secret')=>({projects:{p:{name:'Private project',status:'active',order:1}},tasks:{shared:{title:name,projectId:'p',dueDate:'2026-10-05',notes:'Private notes'}},history:{h:{title:'Private finished',completedAt:'2026-09-28T12:00:00Z'}},maps:{p:{nodes:{b:{parent:'root',kind:'branch',title:'Plan'},late:{parent:'b',kind:'item',title:'Later',due:'2026-10-10',order:0},early:{parent:'b',kind:'item',title:'Earlier',start:'2026-10-01',due:'2026-10-03',order:99},linked:{parent:'b',kind:'item',title:'Linked',taskId:'shared',due:'2026-11-01'},none:{parent:'b',kind:'item',title:'No date'},invalid:{parent:'b',kind:'item',title:'Invalid',due:'2026-02-30'}}}}});
(async()=>{
 const {w,d,db}=await boot({users:{alice:{todo:fixture()},bob:{todo:fixture('Beta only')}},todo:fixture('Owner only')},{user:user('alice')});const M=w.__oym;
 check('private path selected and legacy absent',()=>{assert.equal(M.tasks.shared.title,'Alpha secret');assert(db.listeners.every(l=>l.p.startsWith('users/alice/todo/')))});
 M.setMapPid('p');
 check('chronology uses schedule, not manual map order, and deduplicates linked tasks',()=>assert.deepEqual(Array.from(M.chronoData().dated,t=>t.id),['early','linked','late']));
 check('invalid and missing dates stay unscheduled',()=>assert.equal(M.chronoData().undated.length,2));
 check('invalid dates and leap dates validated',()=>{assert.equal(M.chronoDay('2026-02-30'),null);assert.notEqual(M.chronoDay('2028-02-29'),null)});
 db.ref('users/alice/todo/maps/p/nodes/badEndpoint').set({parent:'b',kind:'item',title:'Bad start',start:'wrong',due:'2026-10-01'});
 check('malformed nonempty endpoint cannot masquerade as a valid schedule',()=>assert(M.chronoData().undated.some(t=>t.id==='badEndpoint')));
 db.ref('users/alice/todo/maps/p/nodes/badEndpoint').set(null);
 M.mapSave('early','due','2026-10-04');
 check('map writes stay in UID workspace',()=>{assert(db.updates.every(u=>Object.keys(u).every(p=>p.startsWith('users/alice/todo/'))));assert.equal(db.get('todo/maps/p/nodes/early/due'),'2026-10-03')});
 d.querySelector('[data-view="map"]').click();await tick();d.querySelector('[data-chrono-mode="clock"]').click();
 check('chronology retains the original map canvas',()=>{assert(d.querySelector('#mapWorld'));assert(!d.querySelector('.orbit-scene'))});
 for(let i=0;i<5;i++)db.ref('users/alice/todo/maps/p/nodes/same'+i).set({parent:'b',kind:'item',title:'Same day '+i,due:'2026-10-10'});await tick();
 check('equal dates retain individually actionable map task rows',()=>{assert.equal(d.querySelectorAll('#mapWorld .mp-item').length,10);assert(!d.querySelector('.clock-hand'))});
 for(let i=0;i<5;i++)db.ref('users/alice/todo/maps/p/nodes/same'+i).set(null);await tick();
 const before=db.updates.length;const scrub=d.querySelector('[data-chrono-scrub]');scrub.value='1000';scrub.dispatchEvent(new w.Event('input',{bubbles:true}));
 check('scrub previews final date without writing or completing tasks',()=>{assert.equal(d.querySelector('output').textContent,'2026-10-10');assert.equal(db.updates.length,before);assert(!M.tasks.shared.completed)});
 d.querySelector('[data-chrono-gantt]').click();await tick();
 check('Gantt has same scrub date and visible playhead',()=>{assert.equal(d.querySelector('#tlHost output').textContent,'2026-10-10');assert(!d.querySelector('.gt-playhead').hidden)});
 d.querySelector('#tlHost [data-chrono-play]').click();await tick(90);
 check('playback advances',()=>{assert.equal(d.querySelector('#tlHost [data-chrono-play]').textContent,'Pause');assert(+d.querySelector('#tlHost [data-chrono-scrub]').value>0)});
 d.querySelector('[data-view="tasks"]').click();await tick();
 check('leaving timeline cancels playback',()=>assert.equal(d.querySelector('#tlHost [data-chrono-play]').textContent,'Play timeline'));
 d.querySelector('[data-project-toggle="p"]').click();
 const row=d.querySelector('[data-id="shared"] [data-act="edit"]');row.click();await tick();const notes=d.querySelector('[data-f="notes"]');notes.value='Delayed Alice note';notes.dispatchEvent(new w.Event('input',{bubbles:true}));
 const stale=db.listeners.find(l=>l.p.endsWith('/tasks')).cb;
 w.__setUser(user('bob'));await tick(750);stale({val:()=>({shared:{title:'Stale Alice'}})});await tick();
 check('account switch drops stale listeners and delayed writes',()=>{assert.equal(M.tasks.shared.title,'Beta only');assert.notEqual(db.get('users/bob/todo/tasks/shared/notes'),'Delayed Alice note');assert(db.listeners.every(l=>l.p.startsWith('users/bob/todo/')))});
 check('account switch clears all prior account DOM and export state',()=>{assert(!d.body.textContent.includes('Alpha secret'));assert.equal(d.querySelector('#mapHost').textContent,'');assert.equal(M.EX.name,'');assert.equal(M.EX.rpid,'')});
 d.querySelector('[data-project-toggle="p"]').click();
 const dragRow=d.querySelector('[data-id="shared"] .t-main'),touch=new w.Event('pointerdown',{bubbles:true});Object.assign(touch,{pointerType:'touch',button:0,pointerId:8,clientX:40,clientY:120});dragRow.dispatchEvent(touch);await tick(300);
 assert(d.querySelector('.drag-ghost'),'touch drag fixture must create the real ghost');
 check('Log out is visible in persistent header',()=>{assert(d.querySelector('.top #signOutBtn'));assert.equal(d.querySelector('#signOutBtn').textContent,'Log out');assert.equal(d.querySelector('#signOutBtn').hidden,false)});
 d.querySelector('#signOutBtn').click();await tick();
 check('logout hides its control',()=>assert.equal(d.querySelector('#signOutBtn').hidden,true));
 check('logout removes touch drag ghost and private drag state',()=>{assert(!d.querySelector('.drag-ghost'));assert(!d.body.classList.contains('drag-active'));assert(!d.body.textContent.includes('Beta only'))});
 check('logout clears task memory and shows account form',()=>{assert.equal(Object.keys(M.tasks).length,0);assert.equal(db.listeners.length,0);assert(!d.querySelector('#gate').hidden)});
 d.querySelector('#authEmail').value='new@example.com';d.querySelector('#authPassword').value='not-a-real-password';d.querySelector('#createAccount').click();await tick();d.querySelector('#resetPassword').click();await tick();
 check('signup and reset invoke Firebase APIs',()=>{assert.equal(w.__authCalls[0][0],'create');assert.equal(w.__authCalls[1][0],'reset')});
 w.__setUser({uid:'owner',email:'dyap123@gmail.com',emailVerified:true});await tick();
 check('verified owner preserves legacy list',()=>assert.equal(M.tasks.shared.title,'Owner only'));
 check('unverified owner address does not select legacy',()=>assert.equal(M.workspaceFor({uid:'imposter',email:'dyap123@gmail.com',emailVerified:false}),'users/imposter/todo'));
 w.close();
 // Google authorization and event reads are independent of login; no live services used.
 let oauth,requests=[],resolveOld;
 const google={accounts:{oauth2:{initTokenClient:o=>(oauth=o,{requestAccessToken(){}}),hasGrantedAllScopes:r=>r.scope==='allowed',revoke:(token,cb)=>cb({})}}};
 const cal=await boot({users:{alice:{todo:fixture()},bob:{todo:fixture()}}},{user:user('alice'),google,fetch:async(url,opt)=>{requests.push({url,opt});return {ok:true,json:async()=>({items:[{summary:'Team meeting',start:{dateTime:'2026-09-28T14:00:00-07:00'},end:{dateTime:'2026-09-28T15:00:00-07:00'}},{summary:'Retreat',start:{date:'2026-09-28'},end:{date:'2026-09-30'}}]})}}});
 cal.d.querySelector('[data-view="calendar"]').click();await tick();
 check('login alone never fetches Calendar',()=>assert.equal(requests.length,0));
 cal.w.__oym.googleCalendarConnect();oauth.callback({access_token:'memory-only',scope:'denied'});await tick();
 check('denied consent does not connect',()=>{assert.equal(requests.length,0);assert.match(cal.d.querySelector('.google-calendar').textContent,/not granted/)});
 cal.w.__oym.googleCalendarConnect();oauth.callback({access_token:'memory-only',scope:'allowed',expires_in:3600});await tick();
 check('real events API called read-only with bounded dates',()=>{assert.match(requests[0].url,/calendar\/v3\/calendars\/primary\/events/);assert.match(requests[0].url,/singleEvents=true/);assert.equal(requests[0].opt.headers.Authorization,'Bearer memory-only');assert.equal(requests[0].opt.cache,'no-store')});
 const days=cal.w.__oym.googleEventDays({start:{date:'2026-09-28'},end:{date:'2026-09-30'}},new Date(2026,8,1),new Date(2026,9,1));
 check('all-day end is exclusive',()=>assert.deepEqual(Array.from(days),['2026-09-28','2026-09-29']));
 check('Google events rendered in calendar',()=>assert.match(cal.d.querySelector('#calHost').textContent,/Team meeting/));
 check('token not persisted in browser storage',()=>assert(!Object.values(cal.w.localStorage).some(v=>String(v).includes('memory-only'))));
 cal.w.fetch=()=>new Promise(resolve=>{resolveOld=resolve});cal.w.__oym.googleCalendarLoad();cal.w.__setUser(user('bob'));await tick();resolveOld({ok:true,json:async()=>({items:[{summary:'Alice leaked event',start:{date:'2026-09-28'},end:{date:'2026-09-29'}}]})});await tick();
 check('late Calendar response cannot enter another account',()=>assert(!cal.d.querySelector('#calHost').textContent.includes('Alice leaked event')));
 cal.w.fetch=async()=>({status:401,ok:false});cal.w.__oym.googleCalendarConnect();oauth.callback({access_token:'expired',scope:'allowed',expires_in:3600});await tick();
 check('401 expires connection and clears events',()=>{assert.match(cal.d.querySelector('.google-calendar').textContent,/expired/);assert(!cal.d.querySelector('[data-google-disconnect]'))});
 let page=0;cal.w.fetch=async()=>({ok:true,json:async()=>++page===1?{items:[],nextPageToken:'next'}:{items:[{summary:'Second page',start:{date:'2026-09-28'},end:{date:'2026-09-29'}}]}});
 cal.w.__oym.googleCalendarConnect();oauth.callback({access_token:'new-token',scope:'allowed',expires_in:3600});await tick(70);
 check('pagination includes later pages',()=>{assert.equal(page,2);assert.match(cal.d.querySelector('#calHost').textContent,/Second page/)});
 cal.d.querySelector('[data-google-disconnect]').click();
 check('disconnect clears displayed calendar events',()=>assert(!cal.d.querySelector('#calHost').textContent.includes('Second page')));
 cal.w.close();
 let reauthProvider;const gu={...user('google'),providerData:[{providerId:'google.com'}],reauthenticateWithPopup(provider){reauthProvider=provider;return Promise.resolve({credential:{accessToken:'reauth-token'}})}};
 let reauthReads=0;const linked=await boot({users:{google:{todo:fixture()}}},{user:gu,fetch:async()=>{reauthReads++;return {ok:true,json:async()=>({items:[]})}}});linked.d.querySelector('[data-view="calendar"]').click();linked.w.__oym.googleCalendarConnect();await tick();
 check('Google sign-in uses identity-checked Firebase reauthentication without client configuration',()=>{assert(reauthProvider);assert.equal(linked.w.__lastScope,'https://www.googleapis.com/auth/calendar.events.readonly');assert.equal(reauthReads,1)});
 gu.reauthenticateWithPopup=()=>Promise.reject({code:'auth/user-mismatch',message:'Mismatch'});linked.w.__oym.googleCalendarConnect();await tick();
 check('different Google identity is rejected',()=>{assert.match(linked.d.querySelector('.google-calendar').textContent,/same Google account/);assert.equal(reauthReads,1)});
 linked.w.close();
 const failedLogout=await boot({users:{alice:{todo:fixture('Retained after failure')}}},{user:user('alice'),signOut:()=>Promise.reject(new Error('Synthetic sign-out failure'))});failedLogout.d.querySelector('#signOutBtn').click();await tick();
 check('failed logout reports error and retains account data',()=>{assert.match(failedLogout.d.querySelector('#toast').textContent,/Could not log out: Synthetic sign-out failure/);assert.equal(failedLogout.d.querySelector('#signOutBtn').hidden,false);assert.equal(failedLogout.w.__oym.tasks.shared.title,'Retained after failure');assert.equal(failedLogout.db.updates.length,0)});failedLogout.w.close();
 console.log(`universal: ${checks} passed`);
})().catch(e=>{console.error(e);process.exit(1)});
