// Real application events and canonical synthetic updates; no live Firebase.
const assert=require('node:assert/strict'),{boot}=require('./app-harness.cjs');
const tick=()=>new Promise(r=>setTimeout(r,70));
const seed={todo:{projects:{p:{name:'Drag fixture',status:'active'}},tasks:{},history:{},maps:{p:{nodes:{b:{kind:'branch',parent:'root',title:'Branch',dx:17,dy:-9},t:{kind:'topic',parent:'b',title:'Topic'},other:{kind:'topic',parent:'b',title:'Destination',order:2},i:{kind:'item',parent:'t',title:'Item',taskId:'linked'}}}}}};
(async()=>{const {w,d,db}=await boot(seed),M=w.__oym;M.setMapPid('p');M.setView('map');await tick();d.elementFromPoint=()=>d.querySelector('#mapStage');
const event=(type,target,x,y,pointerType='mouse',pointerId=1)=>{const e=new w.MouseEvent(type,{bubbles:true,cancelable:true,clientX:x,clientY:y,button:0});Object.assign(e,{pointerType,pointerId});target.dispatchEvent(e)};
const scale=()=>+d.querySelector('#mapWorld').style.transform.match(/scale\(([^)]+)\)/)[1];
const drag=(id,dx,dy,steps=1,type='mouse')=>{const el=d.querySelector(`[data-nid="${id}"] .mp-t`);event('pointerdown',el,100,100,type);for(let n=1;n<=steps;n++)event('pointermove',d,100+dx*n/steps,100+dy*n/steps,type);event('pointerup',d,100+dx,100+dy,type)};
let k=scale(),before=db.updates.length;drag('b',84,45);await tick();assert.equal(db.updates.length,before+1,'one coalesced move persists');assert.deepEqual(JSON.parse(JSON.stringify(db.updates.at(-1))),{'todo/maps/p/nodes/b/dx':Math.round(17+84/k),'todo/maps/p/nodes/b/dy':Math.round(-9+45/k)});assert.equal(db.get('todo/maps/p/nodes/t/dx'),undefined,'branch carries descendants without duplicate offsets');assert(!d.body.classList.contains('mp-dragging'));
d.querySelector('[data-mact="zin"]').click();k=scale();before=db.updates.length;drag('t',-60,24,6);await tick();assert.equal(db.updates.length,before+1);assert.deepEqual(JSON.parse(JSON.stringify(db.updates.at(-1))),{'todo/maps/p/nodes/t/dx':Math.round(-60/k),'todo/maps/p/nodes/t/dy':Math.round(24/k)},'all threshold movement counts at changed zoom');
before=db.updates.length;drag('t',3,2);await tick();assert.equal(db.updates.length,before,'movement below threshold never writes');
// An interrupted drag springs back; the next drag starts from a clean press.
let el=d.querySelector('[data-nid="t"] .mp-t');event('pointerdown',el,100,100);event('pointermove',d,160,140);event('pointercancel',d,160,140);await tick();assert.equal(db.updates.length,before);assert(!d.querySelector('.mp-moving'));
// Mouse fix must leave touch long-press and item drop rules intact.
el=d.querySelector('[data-nid="i"] .t');event('pointerdown',el,100,100,'touch');await new Promise(r=>setTimeout(r,280));const target=d.querySelector('[data-nid="other"]');d.elementFromPoint=()=>target;event('pointermove',d,160,140,'touch');event('pointerup',d,160,140,'touch');await tick();assert.equal(db.get('todo/maps/p/nodes/i/parent'),'other');assert.equal(db.get('todo/maps/p/nodes/i/taskId'),'linked');assert(!d.querySelector('.mp-ghost'));
before=db.updates.length;d.querySelector('[data-chrono-mode="clock"]').click();drag('b',70,40);await tick();assert.equal(db.updates.length,before,'chronology remains read-only');d.querySelector('[data-chrono-mode="map"]').click();
el=d.querySelector('[data-nid="b"] .mp-t');event('pointerdown',el,100,100);event('pointermove',d,160,140);w.__setUser(null);event('pointerup',d,160,140);await tick();assert.equal(db.updates.length,before,'account switch cancels pending drag');assert(!d.body.classList.contains('mp-dragging'));w.close();console.log('widget drag: coalesced/multi-step scaled offsets, threshold/cancel, touch reparent, chronology and account cleanup passed');})().catch(e=>{console.error(e);process.exit(1)});
